### ISSUE TITLE
Allow deleting a project

### ISSUE THREAD

**Issue by simonerom** [machinefi/w3bstream-studio#12]
- [ ] Allow the user to delete a project.

- [ ] If the project is empty (no applets) show a confirmation dialog.

- [ ] If the project contains at least one applet, notify the user that all applets will be stopped and deleted forever if they delete the project

**Comment by simonerom** [comment]
@uu-z I can't find this feature implemented anywhere in w3bstream studio: can you please point me to how to delete a project?

**Comment by uu-z** [comment]
@simonerom 
You can right click the project.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/12439992/213071772-688947cd-77ce-453b-afd0-8f622b8dc14f.png">
