### ISSUE TITLE
Move "Send Event" functionality to the Project object

### ISSUE THREAD

**Issue by simonerom** [machinefi/w3bstream-studio#19]
The Send Event and Copy buttons below:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/11096047/199274887-277b21e2-a596-4869-ad4c-9c8ffa1d8691.png">

should be moved away from the Applet and moved to the Project: in fact, events are sent to a project and not to an applet so those buttons would just be duplicated for each applet in the same project.
Maybe move them at the top of the project page?
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/11096047/199275728-7a66b6b3-9cc5-4423-9cd7-792eb2851183.png">

**Comment by uu-z** [comment]
updated
