### ISSUE TITLE
Fix blockchain monitor API endpoint

### ISSUE THREAD

**Issue by simonerom** [machinefi/w3bstream-studio#35]
The blockchain monitor endpoint API has been changed from /srv-applet-mgr/v0/monitor/<PROJECT_ID> to /srv-applet-mgr/v0/monitor/<PROJECT_NAME>. Please update the frontend.

**Comment by uu-z** [comment]
updated

**Comment by simonerom** [comment]
I think the change is also affecting the delete monitor API (it's not possible to delete a contract monitor once it's rected).

**Comment by uu-z** [comment]
@osdodo  let’s hide the delete monitor button
