### ISSUE TITLE
pnpm i error

### ISSUE THREAD

**Issue by jgoldm** [machinefi/w3bstream-studio#42]
Hello,
When I run
`docker build -f Dockerfile -t ubuntu/w3bstream-studio:main .`,
I get this error: 
Step 8/20 : RUN pnpm i --frozen-lockfile;
 ---> Running in 94d6cc5b6d12
/bin/pnpm: line 0: syntax error: unexpected word (expecting ")")
The command '/bin/sh -c pnpm i --frozen-lockfile;' returned a non-zero code: 2

**Comment by uu-z** [comment]
@jgoldm  we have updated the dockerfile. could you try it again?
