### ISSUE TITLE
"Invalid parameters" error when sending an event from W3bstream Studio

### ISSUE THREAD

**Issue by simonerom** [machinefi/w3bstream-studio#44]
How to reproduce
```
# Configure w3bstream
# 1. deploy the official log example applet
# 2. Create a publisher
# 3. Send a default event from the UI
```
You get the notification: "Invalid parameters"
Sending the curl command is a bit more detailed:
```
curl--location--request POST 'localhost:8888/srv-applet-mgr/v0/event/project_01'--header 'Content-Type: text/plain'--data - raw '{"header":{"event_type":"ANY","pub_id":"001","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQYXlsb2FkIjoiOTAxMDIxMTEzMjE1MjgzMiIsImlzcyI6InczYnN0cmVhbSIsImV4cCI6MTY2ODYxNTExMH0.wiXEpHIcxU7HODApMeNFREXZliyfzRnASW6JPNOfS8A","pub_time":1668611513312},"payload":{"example":"This is an example payload"}}'
```
```js
{
    "key": "badRequest",
    "code": 400000000,
    "msg": "invalid parameters",
    "desc": "",
    "canBeTalk": false,
    "id": "",
    "sources": ["srv-applet-mgr@0.0.1"],
    "fields": [{
        "field": "payload",
        "msg": "json: cannot unmarshal object into Go struct field Event.payload of type string",
        "in": "body"
    }]
}
```

**Comment by simonerom** [comment]
I see that the default event message is now reflecting the example recalled in https://github.com/machinefi/w3bstream-studio/issues/33, however, it seems the "raw string" improvement reported in the same issue is not implemented correctly: if I select payload = JSON from the drop-down I still have to manually escape the double quotes to make it work:
This works:
```
"payload": "{
    \"example\": \"This is an example payload\"
  }"
```

**Comment by Liuhaai** [comment]
same issue for me

**Comment by simonerom** [comment]
Any update on this issue?

Also, notice that when we switch Payload to "TEXT", it should not disable syntax Highlighting.

**Comment by uu-z** [comment]
> Any update on this issue?
> 
> Also, notice that when we switch Payload to "TEXT", it should not disable syntax Highlighting.
> 
> @uu-z

hi @simonerom  sorry for the late reply
you could try using the latest version of studio before merging yet
https://github.com/machinefi/w3bstream/pull/229
it's worked for log wasm with JSON mode

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/12439992/204242507-b242fa83-150a-4269-8057-e82ed15c7dea.png">

**Comment by Liuhaai** [comment]
The fix works for me
