### ISSUE TITLE
Allow to store contracts data in W3bstream studio

### ISSUE THREAD

**Issue by simonerom** [machinefi/w3bstream-studio#65]
We should allow users to store contract info inside W3bstream studio, to easily configure contract monitors.

Example use case:
1. My dapp includes 1 or more smart contracts
2. For each contract I need to monitor, in w3bstream studio I click "Manage contracts > Add contract"
3. I input a label for the contract, the contract address, the ABI json, the chain_id, the block_start (possibly provide  autodetect button). A checkbox to tell if I want to stop indexing at a certain block (if not, then default to 0 and do not show the stop block)
4. Then, when I create a contract monitor, I select the contract from a dropdown, and I select the event name from a dropdown (w3bstream studio uses the contracts data to populate dropdowns), the target project and event type.

Contract data must be editable.

**Comment by uu-z** [comment]
What if we provide this feature outside w3bstream?

For example, 
1. we use spoon (https://app.spoon.limo/) to import and  manage the contracts
2. we provide a plugin in spoon that has a ui panela as you mentioned above to export the needed data(topic?)
3. we just copy/paste the data  into create contract moinitor in studio to finished the rest flow

what do you this about that? @simonerom

**Comment by uu-z** [comment]
> 

ok, we could store the abi of the contract to the indexeddb on the frontend that could implement the select event feat. 
but you may will lose the data if you clear the cache data or something else.

**Comment by simonerom** [comment]
I see. 
You think it would not make sense to have the contracts configuration (address+ABI) as part of a W3bstream project data, along with strategies, contract indexers, etc..?)
@CoderZhi

**Comment by uu-z** [comment]
@simonerom 
If the address + ABI could use for scenarios other than helping select events to create the monitor that we also could store the contract address and ABI to DB rather than just implement it by the frontend to avoid adding more complexity to the DB and backend.
