### ISSUE TITLE
Support Apple M1/M2 for the docker image

### ISSUE THREAD

**Issue by Liuhaai** [machinefi/w3bstream-studio#68]
When the image is booted by docker-compose on the lastest macbook, an error occurs
> no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by imjeson** [comment]
It works on my macbook(M2),

**Comment by imjeson** [comment]
To fix this issue,we should add an "platform" option to docker-compose.yaml.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/12442007/220056348-466babb2-bf76-4ead-8069-d197e2a5385b.png">


https://github.com/compose-spec/compose-spec/blob/master/spec.md#platform

**Comment by uu-z** [comment]
> To fix this issue,we should add an "platform" option to docker-compose.yaml.
> 
> <img alt="image" width="905" src="https://user-images.githubusercontent.com/12442007/220056348-466babb2-bf76-4ead-8069-d197e2a5385b.png">
> 
> https://github.com/compose-spec/compose-spec/blob/master/spec.md#platform

the `platform: linux/x86_64` has added.
