### ISSUE TITLE
can start docker but cannot stop?

### ISSUE THREAD

**Issue by dustinxie** [machinefi/w3bstream-studio#76]
can start the node using command as instructed:
```
docker-compose -p w3bstream -f ./docker-compose.yaml up -d
```
<img width="687" alt="Screen Shot 2023-03-14 at 12 16 46 PM" src="https://user-images.githubusercontent.com/12551272/225113517-20e591e0-254a-4443-a79f-9d3dc84bd61b.png">

but cannot stop using `docker-compose down`, it gives the following, and containers are still running

<img width="374" alt="Screen Shot 2023-03-14 at 12 34 30 PM" src="https://user-images.githubusercontent.com/12551272/225117372-9f4f0f4f-92bc-4ca0-abb8-8c8eaed61730.png">

am I missing sth, like need to start a studio on local network?

**Comment by xianhuawei** [comment]
It seems project-name has changed between up and down.
try
```bash
docker-compose -p w3bstream down
```
<img width="447" alt="image" src="https://user-images.githubusercontent.com/3870801/225166671-a2e2b43d-000b-4c3b-869a-bc66b49c0744.png">
